const Vitasensus = {
	address: {
		mainnet: '',
		testnet: 'vite_40a7f24b11036aaa293a0a9751f66c1d88e7a6a13e9d0cb629', // <your_contract_address>
		localnet: 'vite_22ad191e13ccb892c812244e537bb409785e5831bd88729204',
	},
	abi: [
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ indexed: true, internalType: 'address', name: 'user', type: 'address' },
			],
			name: 'JoinedSpace',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ indexed: true, internalType: 'address', name: 'user', type: 'address' },
			],
			name: 'LeftSpace',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [{ indexed: false, internalType: 'uint256', name: '', type: 'uint256' }],
			name: 'LogUint',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
				{ indexed: true, internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ indexed: true, internalType: 'address', name: 'author', type: 'address' },
				{ indexed: false, internalType: 'string', name: 'title', type: 'string' },
				{ indexed: false, internalType: 'string', name: 'description', type: 'string' },
				{ indexed: false, internalType: 'uint256', name: 'startTime', type: 'uint256' },
				{ indexed: false, internalType: 'uint256', name: 'endTime', type: 'uint256' },
			],
			name: 'ProposalCreated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'uint256', name: 'proposalId', type: 'uint256' },
				{ indexed: true, internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ indexed: false, internalType: 'uint256', name: 'choiceId', type: 'uint256' },
			],
			name: 'ProposalExecuted',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'uint256', name: 'proposalId', type: 'uint256' },
				{ indexed: true, internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ indexed: true, internalType: 'address', name: 'voter', type: 'address' },
			],
			name: 'ProposalVoted',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
				{ indexed: false, internalType: 'address', name: 'admin', type: 'address' },
			],
			name: 'SpaceAdminAdded',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
				{ indexed: false, internalType: 'address', name: 'admin', type: 'address' },
			],
			name: 'SpaceAdminRemoved',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
				{ indexed: false, internalType: 'bytes32', name: 'from', type: 'bytes32' },
				{ indexed: false, internalType: 'bytes32', name: 'to', type: 'bytes32' },
			],
			name: 'SpaceAvatarUpdated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
				{ indexed: true, internalType: 'tokenId', name: 'token', type: 'tokenId' },
				{ indexed: true, internalType: 'bytes32', name: 'name', type: 'bytes32' },
				{ indexed: false, internalType: 'bytes32', name: 'avatar', type: 'bytes32' },
				{ indexed: false, internalType: 'string', name: 'description', type: 'string' },
			],
			name: 'SpaceCreated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
				{ indexed: false, internalType: 'bytes32', name: 'from', type: 'bytes32' },
				{ indexed: false, internalType: 'bytes32', name: 'to', type: 'bytes32' },
			],
			name: 'SpaceDescriptionUpdated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
				{ indexed: false, internalType: 'bytes32', name: 'from', type: 'bytes32' },
				{ indexed: false, internalType: 'bytes32', name: 'to', type: 'bytes32' },
			],
			name: 'SpaceNameUpdated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
				{ indexed: true, internalType: 'address', name: 'from', type: 'address' },
				{ indexed: true, internalType: 'address', name: 'to', type: 'address' },
			],
			name: 'SpaceOwnershipTransferred',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
				{ indexed: true, internalType: 'tokenId', name: 'from', type: 'tokenId' },
				{ indexed: true, internalType: 'tokenId', name: 'to', type: 'tokenId' },
			],
			name: 'SpaceTokenUpdated',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
				{ indexed: false, internalType: 'bytes32', name: 'from', type: 'bytes32' },
				{ indexed: false, internalType: 'bytes32', name: 'to', type: 'bytes32' },
			],
			name: 'SpaceWebsiteUpdated',
			type: 'event',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'address', name: 'newAdmin', type: 'address' },
			],
			name: 'addSpaceAdmin',
			outputs: [],
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'string', name: 'title', type: 'string' },
				{ internalType: 'string', name: 'description', type: 'string' },
				{ internalType: 'uint256', name: 'startTime', type: 'uint256' },
				{ internalType: 'uint256', name: 'endTime', type: 'uint256' },
				{ internalType: 'bytes32[]', name: 'choices', type: 'bytes32[]' },
				{ internalType: 'address[]', name: 'choicesExecutors', type: 'address[]' },
				{ internalType: 'bytes32[]', name: 'choicesData', type: 'bytes32[]' },
			],
			name: 'createProposal',
			outputs: [],
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'bytes32', name: 'name', type: 'bytes32' },
				{ internalType: 'string', name: 'description', type: 'string' },
				{ internalType: 'tokenId', name: 'spaceToken', type: 'tokenId' },
				{ internalType: 'bytes32', name: 'avatar', type: 'bytes32' },
				{ internalType: 'bytes32', name: 'website', type: 'bytes32' },
				{ internalType: 'uint256', name: 'spaceTokenDecimals', type: 'uint256' },
			],
			name: 'createSpace',
			outputs: [],
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'uint256', name: 'proposalId', type: 'uint256' },
			],
			name: 'executeProposal',
			outputs: [],
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			inputs: [{ internalType: 'uint256', name: 'spaceId', type: 'uint256' }],
			name: 'getSpaceAdmins',
			outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [{ internalType: 'uint256', name: 'spaceId', type: 'uint256' }],
			name: 'getSpaceExternal',
			outputs: [
				{ internalType: 'bytes32', name: 'name', type: 'bytes32' },
				{ internalType: 'string', name: 'description', type: 'string' },
				{ internalType: 'tokenId', name: 'token', type: 'tokenId' },
				{ internalType: 'bytes32', name: 'avatar', type: 'bytes32' },
				{ internalType: 'bytes32', name: 'website', type: 'bytes32' },
				{ internalType: 'uint256', name: 'memberCounts', type: 'uint256' },
				{ internalType: 'uint256', name: 'tokenDecimals', type: 'uint256' },
			],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'uint256', name: 'skip', type: 'uint256' },
				{ internalType: 'uint256', name: 'limit', type: 'uint256' },
			],
			name: 'getSpaceMembers',
			outputs: [{ internalType: 'address[]', name: 'members_', type: 'address[]' }],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [{ internalType: 'uint256', name: 'spaceId', type: 'uint256' }],
			name: 'getSpaceOwner',
			outputs: [{ internalType: 'address', name: '', type: 'address' }],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'uint256', name: 'proposalId', type: 'uint256' },
			],
			name: 'getSpaceProposal',
			outputs: [
				{ internalType: 'string', name: 'title', type: 'string' },
				{ internalType: 'string', name: 'description', type: 'string' },
				{ internalType: 'address', name: 'author', type: 'address' },
				{ internalType: 'uint256', name: 'startTime', type: 'uint256' },
				{ internalType: 'uint256', name: 'endTime', type: 'uint256' },
				{ internalType: 'bytes32[]', name: 'choices', type: 'bytes32[]' },
				{ internalType: 'address[]', name: 'choicesExecutors', type: 'address[]' },
				{ internalType: 'bytes32[]', name: 'choicesData', type: 'bytes32[]' },
				{ internalType: 'uint256[]', name: 'votes', type: 'uint256[]' },
			],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'uint256', name: 'proposalId', type: 'uint256' },
			],
			name: 'getSpaceProposalChoices',
			outputs: [{ internalType: 'bytes32[]', name: 'choices', type: 'bytes32[]' }],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'uint256', name: 'proposalId', type: 'uint256' },
				{ internalType: 'uint256', name: 'skip', type: 'uint256' },
				{ internalType: 'uint256', name: 'limit', type: 'uint256' },
			],
			name: 'getSpaceProposalVotes',
			outputs: [
				{ internalType: 'address[]', name: 'voters', type: 'address[]' },
				{ internalType: 'uint256[][]', name: 'votes', type: 'uint256[][]' },
			],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'uint256', name: 'skip', type: 'uint256' },
				{ internalType: 'uint256', name: 'limit', type: 'uint256' },
			],
			name: 'getSpaceProposals',
			outputs: [
				{ internalType: 'uint256[]', name: 'proposalIds', type: 'uint256[]' },
				{ internalType: 'string[]', name: 'titles', type: 'string[]' },
				{ internalType: 'string[]', name: 'descriptions', type: 'string[]' },
				{ internalType: 'uint256[]', name: 'startTimes', type: 'uint256[]' },
				{ internalType: 'uint256[]', name: 'endTimes', type: 'uint256[]' },
				{ internalType: 'uint256[]', name: 'choicesCount', type: 'uint256[]' },
			],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [{ internalType: 'uint256', name: 'spaceId', type: 'uint256' }],
			name: 'getSpaceToken',
			outputs: [{ internalType: 'tokenId', name: '', type: 'tokenId' }],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'skip', type: 'uint256' },
				{ internalType: 'uint256', name: 'limit', type: 'uint256' },
			],
			name: 'getSpaces',
			outputs: [
				{ internalType: 'bytes32[]', name: 'names', type: 'bytes32[]' },
				{ internalType: 'tokenId[]', name: 'tokens', type: 'tokenId[]' },
				{ internalType: 'bytes32[]', name: 'avatars', type: 'bytes32[]' },
				{ internalType: 'bytes32[]', name: 'websites', type: 'bytes32[]' },
				{ internalType: 'uint256[]', name: 'memberCounts', type: 'uint256[]' },
			],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
			name: 'getUserSpaces',
			outputs: [
				{ internalType: 'uint256[]', name: 'spaceIds', type: 'uint256[]' },
				{ internalType: 'bytes32[]', name: 'names', type: 'bytes32[]' },
				{ internalType: 'bytes32[]', name: 'avatars', type: 'bytes32[]' },
			],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [],
			name: 'getZeroAddress',
			outputs: [{ internalType: 'address', name: '', type: 'address' }],
			stateMutability: 'pure',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'uint256', name: 'proposalId', type: 'uint256' },
			],
			name: 'isProposalActive',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'uint256', name: 'proposalId', type: 'uint256' },
			],
			name: 'isProposalClosed',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'uint256', name: 'proposalId', type: 'uint256', value: '1' },
			],
			name: 'isProposalExecuted',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'address', name: 'user', type: 'address' },
			],
			name: 'isSpaceAdmin',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'address', name: 'user', type: 'address' },
			],
			name: 'isSpaceMember',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'address', name: 'user', type: 'address' },
			],
			name: 'isSpaceOwner',
			outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [{ internalType: 'uint256', name: 'spaceId', type: 'uint256' }],
			name: 'joinSpace',
			outputs: [],
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			inputs: [{ internalType: 'uint256', name: 'spaceId', type: 'uint256' }],
			name: 'leaveSpace',
			outputs: [],
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'uint256', name: 'proposalId', type: 'uint256' },
				{ internalType: 'address', name: 'voter', type: 'address' },
			],
			name: 'redeemVotedTokens',
			outputs: [],
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'address', name: 'admin', type: 'address' },
			],
			name: 'removeSpaceAdmin',
			outputs: [],
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			inputs: [],
			name: 'timestamp',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'address', name: 'newOwner', type: 'address' },
			],
			name: 'transferSpaceOwnership',
			outputs: [],
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'spaceId', type: 'uint256' },
				{ internalType: 'uint256', name: 'proposalId', type: 'uint256' },
				{ internalType: 'uint256[]', name: 'votes', type: 'uint256[]' },
			],
			name: 'voteOnProposal',
			outputs: [],
			stateMutability: 'payable',
			type: 'function',
		},
	],
};

export default Vitasensus;
